const test=require('node:test'),assert=require('node:assert/strict'),crypto=require('node:crypto');
const D=require('../functions/hamster-domain');
class HttpsError extends Error{constructor(code,message){super(message);this.code=code;}}
function fixture(){
 const records=new Map(),root='stores/kyrgyz-organics/games/hamster-spin';let queue=Promise.resolve();
 const clone=x=>x===undefined?undefined:structuredClone(x);
 const snap=path=>({id:path.split('/').at(-1),exists:records.has(path),data:()=>clone(records.get(path))});
 const doc=path=>({path,get:async()=>snap(path),update:async data=>records.set(path,{...records.get(path),...data})});
 const db={doc,collection:path=>({where:()=>({get:async()=>({docs:[]})})}),runTransaction(work){const next=queue.then(async()=>{const writes=[];let writing=false;const tx={get:async r=>{assert.equal(writing,false,'Firestore reads must precede all writes');return snap(r.path);},set:(r,v,o)=>{writing=true;writes.push([r.path,v,o?.merge]);},create:(r,v)=>{writing=true;if(records.has(r.path))throw Error('exists');writes.push([r.path,v,false]);},update:(r,v)=>{writing=true;writes.push([r.path,v,true]);}};const result=await work(tx);for(const [path,v,merge]of writes){const value=merge?{...records.get(path)}:{};for(const [k,n]of Object.entries(v))value[k]=n?.increment!==undefined?(value[k]||0)+n.increment:n;records.set(path,clone(value));}return result;});queue=next.catch(()=>{});return next;}};
 const admin={firestore:{FieldValue:{increment:n=>({increment:n})},FieldPath:{documentId:()=> '__name__'}}};
 const api=require('../functions/hamster-game')({db,admin,functions:{https:{onCall:fn=>fn,HttpsError}}});
 const user=(uid='player',verified=true,anonymous=false)=>({uid,token:{email_verified:verified,firebase:{sign_in_provider:anonymous?'anonymous':'password'}}});
 const call=(action,payload={},auth=user())=>api.hamsterGame({auth,data:{action,requestId:crypto.randomUUID(),...payload}});
 const manage=(action,payload={},auth=user('staff'))=>api.hamsterAdmin({auth,data:{action,requestId:crypto.randomUUID(),...payload}});
 records.set('users/staff',{role:'admin',companyId:'kyrgyz-organics'});
 return {records,root,call,manage,user,player:()=>records.get(root+'/players/player')};
}
test('settings reject invalid odds, fractional grants and reward tampering',()=>{assert.throws(()=>D.validateSettings({...D.DEFAULTS,lossPercent:95,jackpotPercent:10}));assert.throws(()=>D.validateSettings({...D.DEFAULTS,purchaseSpins:1.5}));assert.throws(()=>D.validateSettings({...D.DEFAULTS,rewards:[]}));assert.equal(D.validateSettings(D.DEFAULTS).dailySpins.length,7);});
test('odds boundaries produce honest reel patterns and zero reward losses',()=>{for(const [roll,tier,payout]of [[0,'loss',0],[5499,'loss',0],[5500,'pair',5],[9499,'pair',5],[9500,'jackpot',40],[9999,'jackpot',40]]){let first=true;const r=D.roll(D.DEFAULTS,max=>{if(first){first=false;return roll;}return 0;});assert.equal(r.outcome,tier);assert.equal(r.payout,payout);assert.equal(new Set(r.reels).size,tier==='loss'?3:tier==='pair'?2:1);}});
test('daily streak uses Bishkek midnight and resets after missed days',()=>{const now=Date.parse('2026-09-20T18:01:00Z');assert.equal(D.dayKey(now),'2026-09-21');assert.equal(D.nextDailyDay({lastDailyDate:'2026-09-20',dailyDay:6},now),0);assert.equal(D.nextDailyDay({lastDailyDate:'2026-09-19',dailyDay:4},now),0);});
test('guest upgrade keeps balances and cannot use verified-only benefits',async()=>{const f=fixture();await f.call('load',{},f.user('player',false,true));f.player().seeds=21;await f.call('load');assert.equal(f.player().seeds,21);assert.equal(f.player().registered,true);await assert.rejects(f.call('daily',{},f.user('player',false,true)),{code:'failed-precondition'});});
test('spin retries do not double charge; parallel different IDs cannot overspend',async()=>{const f=fixture();await f.call('load');f.player().spins=1;const requestId=crypto.randomUUID();const [a,b]=await Promise.all([f.call('spin',{requestId}),f.call('spin',{requestId})]);assert.deepEqual(a,b);assert.equal(f.player().spins,0);assert.equal(f.player().totalSpins,1);await assert.rejects(f.call('spin'),{code:'failed-precondition'});await assert.rejects(f.call('profile',{requestId,name:'X',theme:'sage'}),{code:'already-exists'});});
test('daily bonus is awarded only once across simultaneous claims',async()=>{const f=fixture();await f.call('load');const out=await Promise.allSettled([f.call('daily'),f.call('daily')]);assert.equal(out.filter(x=>x.status==='fulfilled').length,1);assert.equal(f.player().spins,8);});
test('purchase codes are globally single-use, idempotent and revocable',async()=>{const f=fixture();await f.call('load');await f.call('load',{},f.user('other'));const batch=await f.manage('generateCodes',{count:2,label:'Bread'});const requestId=crypto.randomUUID();const results=await Promise.allSettled([f.call('purchase',{code:batch.tokens[0],requestId}),f.call('purchase',{code:batch.tokens[0]},f.user('other'))]);assert.equal(results.filter(x=>x.status==='fulfilled').length,1);const balance=f.player().spins;await f.call('purchase',{code:batch.tokens[0],requestId});assert.equal(f.player().spins,balance);await f.manage('revokeBatch',{id:batch.id});await assert.rejects(f.call('purchase',{code:batch.tokens[1]}),{code:'failed-precondition'});assert.equal(D.normalizeCode('https://oako.kg/hamster_game/#code='+batch.tokens[0]),batch.tokens[0]);});
test('expired QR and shared product URLs do not award spins',async()=>{const f=fixture();await f.call('load');const batch=await f.manage('generateCodes',{count:1,label:'Expired'});f.records.get(f.root+'/purchaseCodes/'+D.hash(batch.tokens[0])).expiresAt=1;await assert.rejects(f.call('purchase',{code:batch.tokens[0]}),{code:'failed-precondition'});await assert.rejects(f.call('purchase',{code:'https://oako.kg/product.html?id=bread'}),{code:'invalid-argument'});});
test('prices are server-owned and only staff may consume coupons',async()=>{const f=fixture();await f.call('load');f.player().seeds=100;const requestId=crypto.randomUUID();const r=await f.call('redeem',{rewardId:'cookie',cost:0,requestId});assert.equal(f.player().seeds,20);await f.call('redeem',{rewardId:'cookie',cost:0,requestId});assert.equal(f.player().seeds,20);await assert.rejects(f.manage('useCoupon',{code:r.coupon.code},f.user()),{code:'permission-denied'});await f.manage('useCoupon',{code:r.coupon.code});await assert.rejects(f.manage('useCoupon',{code:r.coupon.code}),{code:'already-exists'});});
test('cross-store admins cannot edit game; settings edits detect stale versions',async()=>{const f=fixture();f.records.set('users/outsider',{role:'admin',companyId:'other'});await assert.rejects(f.manage('settings',{settings:D.DEFAULTS,version:1},f.user('outsider')),{code:'permission-denied'});await f.manage('settings',{settings:D.DEFAULTS,version:1});await assert.rejects(f.manage('settings',{settings:D.DEFAULTS,version:1}),{code:'aborted'});});
test('tasks validate progress and claim once; paused game rejects spins',async()=>{const f=fixture();await f.call('load');await assert.rejects(f.call('task',{taskId:'spin3'}),{code:'failed-precondition'});await f.call('profile',{name:'Bun',theme:'sage'});await f.call('task',{taskId:'style'});await assert.rejects(f.call('task',{taskId:'style'}),{code:'already-exists'});await f.manage('settings',{settings:{...D.DEFAULTS,enabled:false},version:1});await assert.rejects(f.call('spin'),{code:'failed-precondition'});});

test('WhatsApp consent requires a phone and explicit choice; opt-out blocks stale admin drafts',async()=>{const f=fixture();await f.call('load');await assert.rejects(f.call('contact',{phone:'not a number',confirmNumber:true,optedIn:true}));await assert.rejects(f.call('contact',{phone:'+996700123456',confirmNumber:true}));await assert.rejects(f.manage('whatsappDraft',{uid:'player'}));await f.call('contact',{phone:'+996 (700) 123-456',confirmNumber:true,optedIn:false});assert.equal(f.player().whatsapp.phone,'+996700123456');assert.equal(f.player().whatsapp.optedIn,false);await assert.rejects(f.manage('whatsappDraft',{uid:'player'}));await f.call('contact',{phone:'+996700123456',confirmNumber:true,optedIn:true});const draft=await f.manage('whatsappDraft',{uid:'player'});assert.match(draft.url,/^https:\/\/wa.me\/996700123456/);assert.ok(f.player().whatsapp.updatedAt);assert.equal(f.player().whatsapp.verified,false);await f.manage('whatsappOptOut',{uid:'player'});await assert.rejects(f.manage('whatsappDraft',{uid:'player'}));await assert.rejects(f.manage('whatsappDraft',{uid:'player'},f.user()));assert.equal([...f.records.keys()].filter(k=>k.includes('/consentHistory/')).length,3);});
test('WhatsApp templates are private staff settings with conflict and image validation',async()=>{const f=fixture();await assert.rejects(f.manage('whatsappTemplate',{text:'Hi',image:'javascript:bad',version:0}));await assert.rejects(f.manage('whatsappTemplate',{text:'Hi',image:'',version:0},f.user()));await f.manage('whatsappTemplate',{text:'A bakery offer',image:'',version:0});assert.equal(f.records.get(f.root+'/communications/whatsapp').version,1);await assert.rejects(f.manage('whatsappTemplate',{text:'Old overwrite',image:'',version:0}));});

test('Verified phone accounts claim benefits without email; typed contact numbers do not verify identity',async()=>{const f=fixture();const phone=f.user('player',false);phone.token.firebase.sign_in_provider='phone';phone.token.phone_number='+996700123456';await f.call('load',{},phone);assert.equal(f.player().authPhone,'+996700123456');await f.call('daily',{},phone);const other=f.user('other',false);await f.call('load',{},other);await f.call('contact',{phone:'+996700123456',confirmNumber:true,optedIn:false},other);await assert.rejects(f.call('daily',{},other));});
