const {chromium}=require('C:/Users/fangb_kyiapn1/.codex/skills/develop-web-game/node_modules/playwright');
const http=require('node:http'),fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const D=require('../functions/hamster-domain'),root=path.resolve(__dirname,'..');
const mock=`const settings=${JSON.stringify(D.DEFAULTS)};let p=${JSON.stringify(D.initialPlayer('ui-test',D.DEFAULTS,Date.now()))};let user={isAnonymous:true,emailVerified:false,email:''};let coupons=[];export const account=()=>user;const snapshot=()=>({player:p,settings,coupons,serverNow:Date.now(),dayKey:'2026-09-22'});export const boot=async()=>snapshot();export const load=async()=>snapshot();export async function register(email,password){user={isAnonymous:false,emailVerified:false,email};return snapshot();}export const refreshVerification=async()=>{user.emailVerified=true;return snapshot();};export const resendVerification=async()=>{};export const resetPassword=async()=>{};export const login=async()=>snapshot();export const logout=async()=>snapshot();export async function mutate(action,data){window.calls=(window.calls||[]).concat({action,data});if(action==='spin'){p.spins--;p.totalSpins++;await new Promise(r=>setTimeout(r,400));return {...snapshot(),outcome:'loss',reels:[0,1,2],payout:0};}if(action==='daily'){p.spins+=3;p.lastDailyDate='2026-09-22';p.dailyDay=0;}if(action==='profile'){p.name=data.name;p.theme=data.theme;p.styled=true;}if(action==='visit')p.visited=true;if(action==='purchase'){if(data.code!=='valid-code')throw Error('This purchase code has already been used.');p.spins+=5;return {...snapshot(),spinsAdded:5};}return snapshot();}`;
(async()=>{fs.mkdirSync(path.join(root,'test-results/hamster'),{recursive:true});
 const server=http.createServer((req,res)=>{let file=path.join(root,decodeURIComponent(new URL(req.url,'http://localhost').pathname));try{if(fs.statSync(file).isDirectory())file=path.join(file,'index.html');res.setHeader('Content-Type',file.endsWith('.js')?'text/javascript':file.endsWith('.css')?'text/css':file.endsWith('.html')?'text/html':'image/png');res.end(fs.readFileSync(file));}catch{res.writeHead(404).end();}}).listen(19826,'127.0.0.1');
 const browser=await chromium.launch({headless:true});try{const page=await browser.newPage({viewport:{width:393,height:650}});const errors=[];page.on('pageerror',e=>errors.push(String(e)));
 await page.route('**/hamster_game/cloud.js',r=>r.fulfill({contentType:'text/javascript',body:mock}));
 await page.goto('http://127.0.0.1:19826/hamster_game/');await page.waitForSelector('#spin:enabled');await page.locator('#spin').click();await page.waitForFunction(()=>!JSON.parse(render_game_to_text()).spinning);let state=await page.evaluate(()=>JSON.parse(render_game_to_text()));assert.equal(state.seeds,0);assert.equal(state.spins,4);assert.match(state.message,/No match/);
 await page.screenshot({path:path.join(root,'test-results/hamster/live-game-mobile.png')});
 await page.locator('.bottom-nav [data-tab="hamster"]').click();await page.locator('[data-action="account"]').click();await page.locator('#account-email').fill('test@example.com');await page.locator('#account-password').fill('test-only-password');await page.locator('[data-action="register"]').click();await page.waitForSelector('[data-action="verify"]');await page.locator('[data-action="verify"]').click();await page.waitForSelector('[data-action="verify"]',{state:'detached'});
 await page.locator('.bottom-nav [data-tab="play"]').click();await page.locator('[data-action="gift"]:enabled').click();await page.waitForFunction(()=>JSON.parse(render_game_to_text()).spins===7);
 await page.locator('.bottom-nav [data-tab="tasks"]').click();await page.locator('[data-action="purchase"]').click();await page.locator('#purchase-code').fill('valid-code');await page.locator('[data-action="claim-code"]').click();await page.waitForFunction(()=>JSON.parse(render_game_to_text()).spins===12);
 await page.locator('.bottom-nav [data-tab="hamster"]').click();await page.locator('#hamster-name').fill('Cloud Bun');await page.locator('[data-action="save-hamster"]').click();await page.waitForFunction(()=>JSON.parse(render_game_to_text()).hamster.name==='Cloud Bun');
 assert.equal(await page.locator('[data-action="refill"],[data-action="reset"],[data-action="use-coupon"]').count(),0);assert.deepEqual(errors,[]);console.log('UI PASS: server loss, signup/verification, daily gift, purchase code, saved hamster, and removal of demo grants.');
 // Mount the real Games tab with a callable transport stub and inspect every section.
 await page.route('**/firebase-config.js',r=>r.fulfill({contentType:'text/javascript',body:'export const auth={};'}));
 const dashboard={settings:D.DEFAULTS,metrics:{players:4,spins:30},days:[],players:[],batches:[],coupons:[]};
 await page.route('**/authenticated-callable.js',r=>r.fulfill({contentType:'text/javascript',body:`export async function invokeAuthenticatedCallable({data}){window.adminCalls=(window.adminCalls||[]).concat(data);return {data:${JSON.stringify(dashboard)}};}`}));
 await page.goto('http://127.0.0.1:19826/hamster_game/');await page.evaluate(async()=>{document.body.innerHTML='<section id="games"><div id="gamesRoot"></div></section>';const {GamesTab}=await import('/admin/tabs/HamsterGameTab.js');window.gamesTab=new GamesTab();await gamesTab.init();});
 for(const section of ['settings','purchase codes','coupons','players','overview']){await page.locator(`[data-section="${section}"]`).click();assert.ok(await page.locator('.hg-admin').isVisible());}
 await page.locator('[data-section="settings"]').click();await page.locator('[name="lossPercent"]').fill('60');await page.locator('#hg-settings button[type="submit"],#hg-settings button').click();await page.waitForFunction(()=>window.adminCalls.some(x=>x.action==='settings'&&x.settings.lossPercent===60));
 await page.setViewportSize({width:1280,height:900});await page.screenshot({path:path.join(root,'test-results/hamster/admin-settings.png'),fullPage:true});console.log('Admin UI PASS: all five sections and settings submission.');
 }finally{await browser.close();server.close();}
})().catch(e=>{console.error(e);process.exit(1);});
