import {HamsterContacts} from './HamsterContacts.js?v=2.2';
import {BaseTab} from './BaseTab.js';
import {auth} from '../../firebase-config.js';
import {invokeAuthenticatedCallable} from '../../authenticated-callable.js';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const date=t=>t?new Date(t).toLocaleString():'';
const id=()=>Array.from(crypto.getRandomValues(new Uint32Array(4)),n=>n.toString(16).padStart(8,'0')).join('');
const table=(headers,rows)=>`<div class="hg-table"><table><thead><tr>${headers.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${r.map(c=>`<td>${c}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`;
export class GamesTab extends BaseTab{
 constructor(){super('games');this.root=document.getElementById('gamesRoot');this.data=null;this.busy=false;this.notice='';this.section='overview';this.contacts=new HamsterContacts(this);}
 async init(){this.root.addEventListener('click',e=>this.click(e));this.root.addEventListener('submit',e=>this.submit(e));await this.load();}
 async onShow(){await this.load();}
 async onStoreChanged(){if(this.isInitialized)await this.load();}
 async call(action,payload={}){return (await invokeAuthenticatedCallable({auth,projectId:'oa-kyrgyz-organic',functionName:'hamsterAdmin',data:{action,...payload}})).data;}
 async load(){try{this.data=await this.call('dashboard');await this.contacts.load();this.render();}catch(e){this.data=null;this.notice=e.message;this.render();}}
 render(){
  const d=this.data;
  this.root.innerHTML=`<div class="hg-admin"><div class="card-heading-row"><div><div class="eyebrow">KYRGYZ ORGANICS · GAMES</div><h2>Lucky Hamster</h2><p>Manage gameplay, purchase spins, and reward collection.</p></div><a class="btn btn-secondary" href="/hamster_game/" target="_blank" rel="noopener">Open game</a></div><p role="status">${esc(this.notice)}</p><nav>${['overview','settings','purchase codes','coupons','players','registered users'].map(x=>`<button class="btn ${x===this.section?'btn-primary':'btn-secondary'}" data-section="${x}">${x}</button>`).join('')}<button class="btn btn-secondary" data-action="refresh">Refresh</button></nav>${!d?'<p>Game data could not be loaded. Check backend deployment and your access to Kyrgyz Organics.</p>':this.section==='registered users'?this.contacts.html():this.section==='overview'?this.overview(d):this.section==='settings'?this.settings(d.settings):this.section==='purchase codes'?this.codes(d.batches):this.section==='coupons'?this.coupons(d.coupons):this.players(d.players)}</div>`;
  if(!document.getElementById('hg-admin-style')){const el=document.createElement('style');el.id='hg-admin-style';el.textContent='.hg-admin{max-width:1200px;margin:auto}.hg-admin nav{display:flex;gap:8px;flex-wrap:wrap;margin:20px 0;text-transform:capitalize}.hg-admin-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(180px,1fr));gap:15px}.hg-admin label{display:flex;flex-direction:column;gap:7px}.hg-admin input,.hg-admin select{padding:10px;border:1px solid #ccc;border-radius:7px}.hg-admin input[type=checkbox]{width:auto}.hg-admin form,.hg-admin article{padding:20px;border:1px solid #ddd;border-radius:12px;margin:15px 0;background:var(--card-bg,#fff)}.hg-admin article b{font-size:26px;display:block}.hg-admin table{border-collapse:collapse;width:100%;font-size:13px}.hg-admin td,.hg-admin th{padding:11px;text-align:left;border-bottom:1px solid #ddd}.hg-table{overflow:auto;margin:20px 0}.hg-admin form .btn{margin-top:18px}.hg-admin p{margin:10px 0}.hg-admin .bonus-inputs{display:flex;flex-wrap:wrap;gap:10px;margin:18px 0}.hg-admin .bonus-inputs input{width:80px}.hg-admin code{overflow-wrap:anywhere}';document.head.append(el);}
 }
 overview(d){const m=d.metrics;return `<div class="hg-admin-grid">${[['Players','players'],['Registered accounts','registrations'],['Total spins','spins'],['Seeds awarded','seedsAwarded'],['Seeds spent','seedsSpent'],['Purchase scans','purchaseClaims'],['Daily gifts','dailyClaims'],['Coupons collected','couponsUsed']].map(([label,k])=>`<article>${label}<b>${m[k]||0}</b></article>`).join('')}</div><p>Observed loss rate: ${m.spins?Math.round((m.losses||0)/m.spins*100):0}%. Server-confirmed actions; dates use Kyrgyzstan time.</p>${table(['Day','Active players','Spins','Wins','Losses','Seeds awarded','Purchase scans','Reward claims'],d.days.map(x=>[x.date,...['activePlayers','spins','wins','losses','seedsAwarded','purchaseClaims','redemptions'].map(k=>x[k]||0)]))}`;}
 settings(s){const fields=[['starterSpins','Guest starting spins',0,20],['lossPercent','No reward chance (%)',1,95],['jackpotPercent','Jackpot chance (%)',1,20],['pairSeeds','Pair reward (seeds)',1,100],['jackpotSeeds','Jackpot reward (seeds)',1,1000],['purchaseSpins','Spins per new purchase code',1,50],['codeExpiryDays','New code validity (days)',1,365]];return `<form id="hg-settings"><h3>Game settings</h3><label>Game availability<select name="enabled"><option value="true" ${s.enabled?'selected':''}>Open</option><option value="false" ${!s.enabled?'selected':''}>Paused</option></select></label><div class="hg-admin-grid">${fields.map(([k,l,min,max])=>`<label>${l}<input name="${k}" type="number" required min="${min}" max="${max}" value="${s[k]}"></label>`).join('')}</div><p>Pair chance is the remainder: currently ${100-s.lossPercent-s.jackpotPercent}%. Losses consume one spin and give zero seeds. Saved seeds are not deducted.</p><h3>Daily gifts</h3><div class="bonus-inputs">${s.dailySpins.map((n,i)=>`<label>Day ${i+1}<input name="day${i}" type="number" min="1" max="30" required value="${n}"></label>`).join('')}</div><p>One gift per Kyrgyzstan calendar day. Missing a day resets the streak; day 7 cycles to day 1.</p><h3>Bakery rewards</h3>${s.rewards.map(r=>`<div class="hg-admin-grid"><label>Name<input name="name_${r.id}" maxlength="70" required value="${esc(r.name)}"></label><label>Seed price<input name="cost_${r.id}" type="number" min="1" max="100000" required value="${r.cost}"></label><label>Available<input type="checkbox" name="active_${r.id}" ${r.active?'checked':''}></label></div>`).join('')}<button class="btn btn-primary">Save game settings</button><p>Generated codes and issued coupons keep their original values.</p></form>`;}
 codes(batches){return `<form id="hg-codes"><h3>Generate purchase reward QRs</h3><p>Use a different code for each bread package or receipt. Protect the label or issue it after payment. A shared product/payment QR does not prove a purchase.</p><div class="hg-admin-grid"><label>Batch / receipt reference<input name="label" maxlength="100" required></label><label>Number of codes<input name="count" type="number" min="1" max="50" value="10" required></label></div><button class="btn btn-primary">Generate codes</button></form>${table(['Batch','Codes','Spins each','Expires','Actions'],batches.map(b=>[esc(b.label)+(b.revoked?' · CANCELLED':''),b.count,b.spins,date(b.expiresAt),`<button class="btn btn-secondary" data-action="print" data-id="${b.id}">Print / PDF</button> <button class="btn btn-secondary" data-action="csv" data-id="${b.id}">CSV</button> ${!b.revoked?`<button class="btn btn-secondary" data-action="revoke" data-id="${b.id}">Cancel unused</button>`:''}`]))}`;}
 coupons(coupons){return `<form id="hg-coupon"><h3>Validate a customer’s coupon</h3><p>Enter the code shown at the counter. Confirm when handing over the treat; it cannot be used again.</p><label>Coupon code<input name="code" required pattern="[a-fA-F0-9]{24}" maxlength="24"></label><button class="btn btn-primary">Mark collected</button></form><p>Most recent 50 claims.</p>${table(['Treat','Code','Status','Claimed'],coupons.map(c=>[esc(c.name),c.code,esc(c.status),date(c.createdAt)]))}`;}
 players(players){return `<p>50 most recently active players.</p>${table(['Hamster','Account','Seeds','Spins left','Played','Wins','Purchase codes','Last activity'],players.map(p=>[esc(p.name),p.registered?'Registered':'Guest',p.seeds,p.spins,p.totalSpins,p.wins,p.purchaseClaims,date(p.updatedAt)]))}`;}
 async submit(event){if(!event.target.id.startsWith('hg-'))return;event.preventDefault();if(this.busy)return;this.busy=true;const button=event.submitter;if(button)button.disabled=true;try{const f=new FormData(event.target);if(event.target.id==='hg-settings'){const settings={...this.data.settings,enabled:f.get('enabled')==='true',dailySpins:Array.from({length:7},(_,i)=>Number(f.get('day'+i)))};for(const k of ['starterSpins','lossPercent','jackpotPercent','pairSeeds','jackpotSeeds','purchaseSpins','codeExpiryDays'])settings[k]=Number(f.get(k));settings.rewards=settings.rewards.map(r=>({...r,name:f.get('name_'+r.id),cost:Number(f.get('cost_'+r.id)),active:f.has('active_'+r.id)}));await this.call('settings',{settings,version:this.data.settings.version});this.notice='Game settings saved.';}
 else if(event.target.id==='hg-codes'){const payload={label:f.get('label'),count:Number(f.get('count'))},key=JSON.stringify(payload);if(this.pendingCodes?.key!==key)this.pendingCodes={key,requestId:id()};await this.call('generateCodes',{...payload,requestId:this.pendingCodes.requestId});this.pendingCodes=null;this.notice='Codes generated. Print the batch below.';}
 else{if(!confirm('Mark this coupon as collected? Hand over the treat after confirmation succeeds.'))return;const result=await this.call('useCoupon',{code:f.get('code')});this.notice=`Collected: ${result.name}`;}await this.load();}catch(e){this.notice=e.message;this.render();}finally{this.busy=false;if(button)button.disabled=false;}}
 async click(event){const b=event.target.closest('button');if(!b||this.busy)return;if(b.dataset.section){this.section=b.dataset.section;this.render();return;}const action=b.dataset.action;if(!action)return;this.busy=true;let popup;if(action==='print')popup=window.open('','_blank');try{if(action==='refresh')await this.load();else if(action==='revoke'){if(!confirm('Cancel every unused code in this batch? Already claimed spins are kept.'))return;await this.call('revokeBatch',{id:b.dataset.id});this.notice='Unused codes cancelled.';await this.load();}else{const batch=await this.call('batch',{id:b.dataset.id});if(action==='print')await this.print(batch,popup);if(action==='csv')this.csv(batch);}}catch(e){popup?.close();this.notice=e.message;this.render();}finally{this.busy=false;}}
 async qr(){if(window.QRCode)return window.QRCode;await new Promise((resolve,reject)=>{const script=document.createElement('script');script.src='/hamster_game/vendor/qrcode.min.js';script.onload=resolve;script.onerror=reject;document.head.append(script);});return window.QRCode;}
 link(token){return `https://oako.kg/hamster_game/#code=${token}`;}
 async print(batch,popup){if(!popup)throw Error('Allow popups to print QR labels.');const qr=await this.qr();const cards=await Promise.all(batch.tokens.map(async token=>{const url=await qr.toDataURL(this.link(token),{width:240,margin:2});return `<article><h3>Kyrgyz Organics</h3><img src="${url}" width="160" height="160"><b>Scan for ${batch.spins} hamster spins</b><p>One purchase · one use</p><small>${token}</small><p>Valid until ${new Date(batch.expiresAt).toLocaleDateString()}</p></article>`;}));popup.document.write(`<!doctype html><html><head><title>Purchase QR labels</title><style>body{font:13px Arial;margin:20px}.labels{display:grid;grid-template-columns:repeat(3,1fr);gap:12px}article{border:1px dashed #aaa;padding:10px;text-align:center;break-inside:avoid}img{display:block;margin:auto}small{font-size:8px;overflow-wrap:anywhere}@media print{button{display:none}}</style></head><body><h1>${esc(batch.label)}${batch.revoked?' — CANCELLED':''}</h1><button onclick="window.print()">Print / save as PDF</button><div class="labels">${cards.join('')}</div></body></html>`);popup.document.close();}
 csv(batch){const text='code,url,spins,expires\n'+batch.tokens.map(t=>`${t},${this.link(t)},${batch.spins},${new Date(batch.expiresAt).toISOString()}`).join('\n');const url=URL.createObjectURL(new Blob([text],{type:'text/csv'}));const a=document.createElement('a');a.href=url;a.download=`hamster-codes-${batch.id}.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
}
