const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const OPT_OUT='User has opted out of receiving WhatsApp messages.';
export class HamsterContacts {
 constructor(host){this.host=host;this.users=[];this.template={};this.next=null;this.busy=false;this.loaded=false;this.imageDraft=null;host.root.addEventListener('click',e=>{const b=e.target.closest('[data-contact-action]');if(b&&!b.disabled)this.action(b);});host.root.addEventListener('submit',e=>{if(e.target.id==='contact-template'){e.preventDefault();this.save(e.target);}});}
 async load(more=false){const result=await this.host.call('registeredUsers',more?{after:this.next}:{});this.users=more?[...this.users,...result.users]:result.users;this.next=result.next;this.template=result.template;this.loaded=true;}
 html(){return `<h3>Registered users</h3><p>Only registered accounts are listed. Number ownership is user-confirmed, not independently verified. Missing consent is treated as opted out.</p><form id="contact-template"><h3>Saved WhatsApp message and picture</h3><label>Message<textarea name="message" maxlength="2000" rows="4" style="width:100%">${esc(this.template.text||'')}</textarea></label><label>Picture (optional)<input name="picture" type="file" accept="image/png,image/jpeg,image/webp"></label>${this.template.image?`<img src="${this.template.image}" alt="Saved message picture" style="max-width:180px;max-height:150px"><label><input name="removePicture" type="checkbox">Remove saved picture</label>`:''}<button class="btn btn-primary">Save message / picture</button><p>Open a chat draft, then send it in WhatsApp. For a picture, copy it and paste into that chat, or save it and attach it. Nothing is sent automatically. Record STOP replies using “Opt out”.</p></form><div class="hg-table"><table><thead><tr><th>Hamster / email</th><th>WhatsApp</th><th>Marketing consent</th><th>Actions</th></tr></thead><tbody>${this.users.map(p=>{const enabled=p.whatsapp?.optedIn===true&&p.whatsapp?.phone;const tip=enabled?'Open a WhatsApp draft':OPT_OUT;return `<tr><td>${esc(p.name)}<br>${esc(p.email||'Email unavailable')}</td><td>${esc(p.whatsapp?.phone||'Not supplied')}</td><td>${enabled?'Opted in':'Opted out / no consent'}<br><small>${p.whatsapp?.updatedAt?new Date(p.whatsapp.updatedAt).toLocaleString():''}</small></td><td><span tabindex="0" title="${tip}" aria-label="${tip}"><button class="btn btn-secondary" data-contact-action="open" data-uid="${esc(p.id)}" ${enabled?'':'disabled style="opacity:.4;pointer-events:none"'}>Open WhatsApp</button></span> ${['copy','download'].map(a=>`<span tabindex="0" title="${enabled?(this.template.image?'Prepare saved picture':'Save a picture first'):OPT_OUT}"><button class="btn btn-secondary" data-contact-action="${a}" data-uid="${esc(p.id)}" ${enabled&&this.template.image?'':'disabled style="opacity:.4;pointer-events:none"'}>${a==='copy'?'Copy picture':'Save picture'}</button></span>`).join(' ')} ${enabled?`<button class="btn btn-secondary" data-contact-action="optout" data-uid="${esc(p.id)}">Opt out</button>`:''}</td></tr>`;}).join('')}</tbody></table></div>${this.loaded&&!this.users.length?'<p>No registered players yet.</p>':''}${this.next?'<button class="btn btn-secondary" data-contact-action="more">Load more registered users</button>':''}`;}
 async save(form){if(this.busy)return;this.busy=true;try{const file=form.elements.picture.files[0];let image=form.elements.removePicture?.checked?'':this.template.image||'';if(file){if(!['image/png','image/jpeg','image/webp'].includes(file.type))throw Error('Choose a PNG, JPEG or WebP image.');const bitmap=await createImageBitmap(file),canvas=document.createElement('canvas'),scale=Math.min(1,1000/Math.max(bitmap.width,bitmap.height));canvas.width=Math.round(bitmap.width*scale);canvas.height=Math.round(bitmap.height*scale);const ctx=canvas.getContext('2d');ctx.fillStyle='#fff';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.drawImage(bitmap,0,0,canvas.width,canvas.height);bitmap.close();image=canvas.toDataURL('image/jpeg',.8);if(image.length>700000)throw Error('Please choose a smaller picture.');}await this.host.call('whatsappTemplate',{text:form.elements.message.value,image,version:this.template.version||0});await this.load();this.host.notice='WhatsApp message and picture saved.';}catch(e){this.host.notice=e.message;}finally{this.busy=false;this.host.render();}}
 async action(button){if(this.busy)return;const action=button.dataset.contactAction;this.busy=true;let popup;try{
  if(action==='more'){await this.load(true);this.host.render();return;}
  if(action==='optout'){if(!confirm('Record this user’s request to stop WhatsApp messages?'))return;await this.host.call('whatsappOptOut',{uid:button.dataset.uid});await this.load();this.host.notice='User opted out. Messaging is disabled.';this.host.render();return;}
  if(action==='open'){popup=window.open('about:blank','_blank');if(!popup)throw Error('Allow popups to open WhatsApp.');popup.opener=null;}
  const draftPromise=this.host.call('whatsappDraft',{uid:button.dataset.uid});
  if(action==='copy'){
   if(!navigator.clipboard?.write||!window.ClipboardItem){await draftPromise;throw Error('Copying pictures is unavailable in this browser. Use Save picture, then attach it in WhatsApp.');}
   const png=draftPromise.then(async d=>{if(!d.image)throw Error('Save a picture first.');const bitmap=await createImageBitmap(await (await fetch(d.image)).blob()),canvas=document.createElement('canvas');canvas.width=bitmap.width;canvas.height=bitmap.height;canvas.getContext('2d').drawImage(bitmap,0,0);bitmap.close();return new Promise(resolve=>canvas.toBlob(resolve,'image/png'));});
   await navigator.clipboard.write([new ClipboardItem({'image/png':png})]);this.host.notice='Picture copied. Open WhatsApp and paste it into the chat.';
  }else{const draft=await draftPromise;if(action==='open')popup.location.replace(draft.url);else{if(!draft.image)throw Error('Save a picture first.');const link=document.createElement('a');link.href=draft.image;link.download='kyrgyz-organics-whatsapp.jpg';link.click();this.host.notice='Picture saved. Attach it to the WhatsApp chat.';}}
 }catch(e){popup?.close();this.host.notice=e.message;await this.load().catch(()=>{});}finally{this.busy=false;this.host.render();}}
}
