import * as cloud from './cloud.js';

const asset = './assets/';
const icons = {
  play: '<path d="M8 4h8l4 5 1 9a2 2 0 0 1-3 2l-4-3h-4l-4 3a2 2 0 0 1-3-2l1-9z"/><path d="M7 10v4m-2-2h4m6-1h.01m3 3h.01"/>',
  rewards: '<path d="M3 8h18v5H3zM5 13v8h14v-8M12 8v13"/><path d="M12 8C4 9 4 1 8 3c3 1 4 5 4 5s1-4 4-5c4-2 4 6-4 5z"/>',
  tasks: '<path d="M9 5H5v16h14V5h-4M9 3h6v4H9zM8 13l3 3 5-6"/>',
  hamster: '<path d="M6 8C0 2 7 0 9 6m6 0c2-6 9-4 3 2"/><path d="M3 14c0-6 4-8 9-8s9 2 9 8-4 8-9 8-9-2-9-8zM8 12h.01M16 12h.01M10 16l2 2 2-2"/>',
  seed: '<path d="M5 19C-2 7 13 2 20 3c1 9-3 20-15 16zM5 19l10-10"/>',
  spin: '<path d="M20 8a8 8 0 1 0 0 8M20 3v5h-5"/>',
  arrow: '<path d="m9 5 7 7-7 7"/>',
  check: '<path d="m5 12 4 4L19 6"/>',
  sound: '<path d="M11 4 5 9H2v6h3l6 5zM15 8a6 6 0 0 1 0 8m3-11a10 10 0 0 1 0 14"/>',
  info: '<circle cx="12" cy="12" r="9"/><path d="M12 11v6m0-10h.01"/>',
  star: '<path d="m12 2 3 7 7 1-5 5 1 7-6-4-6 4 1-7-5-5 7-1z"/>',
  reset: '<path d="M4 8a8 8 0 1 1 0 8M4 3v5h5"/>'
};
const icon = (name, cls='') => `<svg class="icon ${cls}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${icons[name] || icons.star}</svg>`;
const symbols = [
  {name:'Sourdough', img:'symbols/symbol-bread-classic.png'},
  {name:'Cookie', img:'symbols/symbol-chocolate-cookies.png'},
  {name:'Golden loaf', img:'symbols/symbol-bread-loaf.png'},
  {name:'Star cookie', img:'symbols/symbol-star-cookies.png'}
];
let products = [
  {id:'cookie', name:'A little cookie joy', description:'One chocolate chip cookie', cost:80, img:'symbols/symbol-chocolate-cookies.png', color:'peach'},
  {id:'bread', name:'Your daily bread', description:'A freshly baked sourdough loaf', cost:180, img:'rewards/reward-bread-classic.png', color:'butter'},
  {id:'tea', name:'A cozy tea break', description:'A warm cup, on your hamster', cost:120, img:'rewards/reward-tea.png', color:'sage'},
  {id:'box', name:'The happy baker bag', description:'A little assortment of baked treats', cost:400, img:'rewards/reward-bakery-bag.png', color:'lilac'}
];
const tasks = [
  {id:'spin3', name:'Let the good times roll', detail:'Play 3 spins', target:3, reward:2, glyph:'play'},
  {id:'win2', name:'Find your lucky streak', detail:'Match a pair or better 2 times', target:2, reward:2, glyph:'star'},
  {id:'visit', name:'Window-shop the bakery', detail:'Visit the Rewards tab', target:1, reward:1, glyph:'rewards'},
  {id:'style', name:'A hamster of your own', detail:'Save your hamster’s name and style', target:1, reward:1, glyph:'hamster'}
];
let gifts = [3,5,5,8,10,12,20];
const fresh = () => ({seeds:0, spins:0, totalSpins:0, wins:0, earned:0, claimedTasks:[], claimedDays:[], visited:false, styled:false, coupons:[], name:'Bun', theme:'sage', sound:false});
let state = fresh();

let tab='play', spinning=false, reels=[0,1,2], elapsed=0, stopped=0, pending=null, message='A little luck. A lot of delicious possibilities.', lastPayout=0, modalReturn=null;
let draft={name:state.name,theme:state.theme};
let settings={}, serverDay='', busy=false, connected=false, serverResult=null, serverOffset=0;
const reactionImages={normal:'assets/hamster.png',small:'assets/hamster-small.png',pair:'assets/hamster-pair.png',jackpot:'assets/hamster-jackpot.png'};
const reactionLabels={normal:'your fluffy hamster baker',small:'a happy wink for your win',pair:'a delighted smile for your big win',jackpot:'a jackpot celebration'};
let reaction='normal',reactionRemaining=0,reactionTimer=null;
// Decode once: reel cycling and reaction swaps never wait for an image download.
const imageSources=new Map();
const imageSource=src=>imageSources.get(src)||src;
let artworkReady=false;
const readyImages=Promise.all([...symbols.map(s=>asset+s.img),...Object.values(reactionImages)].map(async src=>{
 try{const response=await fetch(src);if(!response.ok)throw new Error('Artwork unavailable');const url=URL.createObjectURL(await response.blob());const image=new Image();image.src=url;await image.decode();imageSources.set(src,url);return image;}catch{return null;}
})).then(images=>{artworkReady=true;if(document.getElementById('spin')){syncSpinUI();paintReaction();}return images;});
const app=document.getElementById('app');
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function save(){ /* Balances are saved only by authenticated server transactions. */ }
const img=(path,alt,cls='')=>`<img class="${cls}" src="${asset+path}" alt="${esc(alt)}" draggable="false">`;
function header(){return `<header class="topbar"><a class="brand" href="#play" data-tab="play"><span class="brand-mark">${icon('seed')}</span><span>Kyrgyz Organics<small>A LITTLE GOODNESS, EVERY DAY</small></span></a><div class="top-actions"><span class="demo-badge"><i></i> Bakery club</span><button class="icon-button" data-action="sound" aria-label="${state.sound?'Mute':'Enable'} sound" aria-pressed="${state.sound}" title="Toggle sound">${icon('sound')}<span class="sound-state">${state.sound?'ON':'OFF'}</span></button></div></header><div class="page-heading"><div><div class="eyebrow">THE BAKERY IS OPEN</div><h1>${({play:'Lucky Hamster',rewards:'Little seeds. Big treats.',tasks:'A little adventure.',hamster:'Meet your little baker.'})[tab]}</h1><p>${({play:'Play a little. Grow a little. Treat yourself.',rewards:'Turn your good luck into something delicious.',tasks:'Small adventures, a few extra spins.',hamster:'A soft little sidekick, with a style all their own.'})[tab]}</p></div><div class="wallet"><div><span class="coin">${icon('seed')}</span><span><b id="seed-count">${state.seeds.toLocaleString()}</b><small>Seeds</small></span></div><span class="wallet-divider"></span><div><span class="spin-token">${icon('spin')}</span><span><b id="spin-count">${state.spins}</b><small>Spins</small></span></div></div></div>`;}
function mascot(theme=state.theme){return `<div class="mascot-spot ${theme}"><span class="spark spark-one">✦</span><span class="spark spark-two">✧</span><span class="spark spark-three">✦</span><div class="mascot-halo"></div><img class="mascot" width="1024" height="1536" src="${tab==='play'?reactionImages[reaction]:reactionImages.normal}" alt="${esc(state.name)}, your fluffy hamster baker"><span class="mascot-shadow"></span></div>`;}
function giftStrip(){const claimed=state.lastDailyDate===serverDay,day=claimed?state.dailyDay:nextGiftDay();return `<section class="daily-card"><div class="daily-heading"><span class="gift-icon">${icon('rewards')}</span><div><h3>A gift, just for you</h3><p>${claimed?'Come back tomorrow for more spins.':'Your daily bakery break.'}</p></div></div><div class="gift-days">${gifts.map((n,i)=>`<button class="gift-day ${i===day?'current':''}" data-action="gift" ${claimed||i!==day?'disabled':''}><span>Day ${i+1}</span><b>${claimed&&i===day?icon('check'):icon('spin')}</b><small>+${n}</small></button>`).join('')}</div><p class="demo-note">One gift per day · resets at midnight in Kyrgyzstan.</p></section>`;}
function play(){return `<main class="play-layout"><section class="machine-card"><div class="machine-heading"><span>${icon('seed')} THE LUCKY BAKERY</span><button class="text-button" data-action="odds">How to play ${icon('info')}</button></div><div class="reel-mascot ${state.theme}"><span class="mascot-caption">Small seeds.<br>Happy moments.</span>${mascot()}<span class="mascot-caption"><b>${esc(state.name)}</b><br>is feeling lucky ♡</span></div><div class="machine"><div class="machine-top"><i></i><i></i><span>BAKED WITH A LITTLE LUCK</span><i></i><i></i></div><div class="reel-frame">${reels.map((s,i)=>`<div class="reel ${spinning?'rolling':''}" data-reel="${i}"><span class="reel-flourish">✦</span>${img(symbols[s].img,symbols[s].name)}<span class="reel-caption">${symbols[s].name}</span></div>`).join('')}</div><div class="machine-base"><span>✦</span><span>MAKE TODAY A LITTLE SWEETER</span><span>✦</span></div></div><div class="result-message ${lastPayout>=30?'winning':''}" role="status" aria-live="polite">${message}</div><button id="spin" class="spin-button" data-action="spin" ${spinning?'disabled':''}>${icon('spin')}<span>${spinning?'A little luck is baking…':state.spins?'Let’s spin!':'Get more spins'}</span><small>${spinning?'':state.spins?'1 spin':''}</small></button><div class="spin-footnote"><span>${icon('seed')} Some spins win seeds. Some don’t.</span><span>Space to spin</span></div></section>${giftStrip()}</main><section class="below-strip"><span class="mini-treat">${img('symbols/symbol-bread-classic.png','Fresh bread')}</span><div><b>Good luck tastes even better.</b><p>Save your seeds for a treat from our bakery.</p></div><button class="text-button" data-tab="rewards">Explore rewards ${icon('arrow')}</button></section>`;}
function rewards(){return `<main><div class="section-row"><div><span class="eyebrow">FRESH FROM THE OVEN</span><h2>The treat counter</h2></div><span class="soft-tag">Bakery rewards</span></div><div class="product-grid">${products.map(p=>`<article class="product-card"><div class="product-art ${p.color}">${img(p.img,p.name)}<span class="product-label">BAKED WITH LOVE</span></div><div class="product-body"><h3>${esc(p.name)}</h3><p>${p.description}</p><div class="product-bottom"><b>${icon('seed')} ${p.cost}</b><button class="button" data-action="redeem" data-id="${p.id}" ${state.seeds<p.cost?'disabled':''}>${state.seeds<p.cost?'Keep growing':'Get treat'} ${icon('arrow')}</button></div></div></article>`).join('')}</div><div class="section-row coupons-heading"><div><span class="eyebrow">SAVED FOR A SWEET MOMENT</span><h2>Your little stash</h2></div><span class="soft-tag">${state.coupons.filter(c=>!c.used).length} ready to enjoy</span></div><div class="coupon-list">${state.coupons.length?state.coupons.map(c=>`<article class="coupon ${c.used?'used':''}"><span class="coupon-icon">${icon('rewards')}</span><div><h3>${esc(c.name)}</h3><p>${c.used?'Enjoyed at the bakery':'Ready to show at the bakery'}</p><code>${c.code}</code></div><button class="button secondary" data-action="coupon" data-id="${c.id}" ${c.used?'disabled':''}>${c.used?'Enjoyed': 'View coupon'}</button></article>`).join(''):`<div class="empty-state">${icon('rewards')}<h3>A little space for something sweet.</h3><p>Pick a treat above. Your coupons will appear here.</p></div>`}</div></main>`;}
function taskProgress(id){return ({spin3:state.totalSpins,win2:state.wins,visit:Number(state.visited),style:Number(state.styled)})[id];}
function tasksView(){return `${purchasePanel()}<main class="tasks-layout"><section class="task-intro sage"><span class="pill">YOUR DAILY DOSE OF GOOD</span><h2>Little things.<br><em>Lovely rewards.</em></h2><p>A few moments of play, a few more chances to win.</p>${mascot()}<div class="intro-stat"><b>${state.claimedTasks.length} / ${tasks.length}</b><span>adventures completed</span></div></section><section class="task-list">${tasks.map(t=>{const value=Math.min(taskProgress(t.id),t.target), done=state.claimedTasks.includes(t.id);return `<article class="task-card"><span class="task-icon ${t.id}">${icon(t.glyph)}</span><div class="task-copy"><span class="eyebrow">+${t.reward} SPINS</span><h3>${t.name}</h3><p>${t.detail}</p><div class="progress-track"><span style="width:${value/t.target*100}%"></span></div><small>${value} / ${t.target} ${done?'· Reward collected':''}</small></div><button class="button ${done?'secondary':''}" data-action="task" data-id="${t.id}" ${done?'disabled':''}>${done?icon('check'):value>=t.target?'Claim': 'Go '+icon('arrow')}</button></article>`}).join('')}<div class="task-tip">${icon('info')} Every task can be claimed once. Complete a task to claim its reward.</div></section></main>`;}
function hamster(){return `<main class="hamster-layout"><section class="profile-scene ${draft.theme}"><span class="pill">YOUR BAKERY BESTIE</span>${mascot(draft.theme)}<h2 id="preview-name">${esc(draft.name||'Bun')}</h2><p>Apprentice baker · Professional snack lover</p><div class="profile-stats"><div><b>${state.totalSpins}</b><span>Spins played</span></div><div><b>${state.wins}</b><span>Lucky matches</span></div><div><b>${state.earned}</b><span>Seeds won</span></div></div></section><div class="customizer"><section class="panel"><span class="eyebrow">MAKE YOURSELF AT HOME</span><h2>A little personality.</h2><label for="hamster-name">What should we call your hamster?</label><input id="hamster-name" maxlength="18" value="${esc(draft.name)}" placeholder="Bun"><p class="input-hint">Every great baker needs a great name.</p><label>Pick a cozy corner</label><div class="theme-options">${[['sage','Sage garden'],['peach','Peach kitchen'],['lilac','Lavender nook']].map(([key,label])=>`<button class="theme-option ${key} ${draft.theme===key?'selected':''}" data-action="theme" data-theme="${key}" aria-pressed="${draft.theme===key}"><span>${draft.theme===key?icon('check'):''}</span>${label}</button>`).join('')}</div><button class="button wide" data-action="save-hamster">Save my hamster ${icon('check')}</button></section>${accountPanel()}</div></main>`;}
function render(){app.innerHTML=`<div class="shell screen-${tab}">${header()}${({play,rewards,tasks:tasksView,hamster})[tab]()}<footer class="footer"><span>Made for little moments of joy.</span><span>Progress saved to your account</span></footer></div><nav class="bottom-nav" aria-label="Game navigation">${['play','rewards','tasks','hamster'].map(t=>`<button data-tab="${t}" class="${tab===t?'active':''}" ${tab===t?'aria-current="page"':''}>${icon(t)}<span>${({play:'Play',rewards:'Rewards',tasks:'Tasks',hamster:'My hamster'})[t]}</span>${t==='tasks'&&tasks.some(x=>taskProgress(x.id)>=x.target&&!state.claimedTasks.includes(x.id))?'<i class="nav-dot"></i>':''}</button>`).join('')}</nav>`;if(tab==='play'){syncSpinUI();paintReaction();}}
function go(next){if(!['play','rewards','tasks','hamster'].includes(next))return;if(spinning||busy)return toast('Please wait for this action to finish.');setReaction('normal');tab=next;if(tab==='rewards'&&!state.visited)run('visit').catch(showCloudError);if(tab==='hamster')draft={name:state.name,theme:state.theme};render();window.scrollTo({top:0,behavior:'instant'});}
function toast(text){const el=document.createElement('div');el.className='toast';el.textContent=text;document.getElementById('toasts').append(el);setTimeout(()=>el.remove(),3600);}
let audio;
function tone(freq=620,duration=.1){if(!state.sound)return;try {audio ||= new (window.AudioContext||window.webkitAudioContext)();audio.resume();const o=audio.createOscillator(),g=audio.createGain();o.type='sine';o.frequency.value=freq;g.gain.setValueAtTime(.065,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+duration);o.connect(g);g.connect(audio.destination);o.start();o.stop(audio.currentTime+duration);}catch{}}
function paintReaction(){
 const image=document.querySelector('.reel-mascot .mascot');
 if(!image)return;
 image.src=imageSource(reactionImages[reaction]);
 image.alt=`${state.name}, ${reactionLabels[reaction]}`;
 image.closest('.reel-mascot').dataset.reaction=reaction;
}
function setReaction(next){
 clearTimeout(reactionTimer);reaction=next;reactionRemaining=next==='normal'?0:2500;paintReaction();
 if(reactionRemaining)reactionTimer=setTimeout(()=>setReaction('normal'),2500);
}
function paintReel(index,symbolIndex){
 const node=document.querySelector(`[data-reel="${index}"]`);
 if(!node||node.dataset.symbol===String(symbolIndex))return;
 node.dataset.symbol=String(symbolIndex);
 const image=node.querySelector('img');image.src=imageSource(asset+symbols[symbolIndex].img);image.alt=symbols[symbolIndex].name;
 node.querySelector('.reel-caption').textContent=symbols[symbolIndex].name;
}
function syncSpinUI(){
 // Keep the scene and mascot nodes mounted; update only changing game controls.
 document.getElementById('seed-count').textContent=state.seeds.toLocaleString();
 document.getElementById('spin-count').textContent=state.spins;
 const button=document.getElementById('spin');button.disabled=spinning||!artworkReady;
 button.querySelector('span').textContent=!artworkReady?'Warming up…':spinning?'Spinning…':state.spins?'Let’s spin!':'Get more spins';
 button.querySelector('small').textContent=spinning?'':state.spins?'1 spin':'';
 const result=document.querySelector('.result-message');result.textContent=message;result.classList.toggle('winning',lastPayout>=30);
 document.querySelectorAll('[data-reel]').forEach((node,i)=>{node.classList.toggle('rolling',spinning);if(!spinning)paintReel(i,reels[i]);});
 const tasksButton=document.querySelector('.bottom-nav [data-tab="tasks"]');
 const hasReward=tasks.some(t=>taskProgress(t.id)>=t.target&&!state.claimedTasks.includes(t.id));
 if(hasReward&&!tasksButton.querySelector('.nav-dot'))tasksButton.insertAdjacentHTML('beforeend','<i class="nav-dot"></i>');
}
async function startSpin(){if(spinning||busy||!artworkReady)return;if(!settings.enabled)return toast('The game is taking a short break.');if(!state.spins)return openMoreSpins();setReaction('normal');serverResult=null;pending=null;spinning=true;elapsed=0;stopped=0;lastPayout=0;message='Something sweet is on its way…';syncSpinUI();tone(360,.12);try{serverResult=await cloud.mutate('spin');pending=serverResult.reels;if(elapsed>=1700)settle();}catch(e){spinning=false;message='Spin could not be confirmed. Please retry.';syncSpinUI();showCloudError(e);}}
function settle(){if(!serverResult)return;spinning=false;reels=serverResult.reels;lastPayout=serverResult.payout;applySnapshot(serverResult);message=serverResult.outcome==='loss'?'No match this time. Your next spin could be the one!':serverResult.outcome==='jackpot'?`Sweet jackpot! +${lastPayout} seeds.`:`A lovely little match! +${lastPayout} seeds.`;syncSpinUI();setReaction(serverResult.outcome==='loss'?'normal':serverResult.outcome==='jackpot'?'jackpot':lastPayout>=10?'pair':'small');tone(lastPayout?700:280,.2);if(lastPayout)confetti();serverResult=null;}
function advance(ms){if(reactionRemaining){reactionRemaining=Math.max(0,reactionRemaining-ms);if(!reactionRemaining)setReaction('normal');}if(!spinning)return;elapsed+=ms;for(let i=0;i<3;i++){const node=document.querySelector(`[data-reel="${i}"]`);if(!node)continue;const stopAt=850+i*330;const idx=pending&&elapsed>=stopAt?pending[i]:Math.floor((elapsed+i*137)/85)%symbols.length;paintReel(i,idx);if(pending&&elapsed>=stopAt){node.classList.remove('rolling');if(stopped<=i){stopped=i+1;tone(460+i*140,.08);}}}if(elapsed>=1700&&serverResult)settle();}
let previous=performance.now();function frame(now){advance(Math.min(now-previous,70));previous=now;requestAnimationFrame(frame);}requestAnimationFrame(frame);
window.advanceTime=async ms=>{advance(ms);};
window.render_game_to_text=()=>JSON.stringify({tab,spinning,reaction,reactionRemaining,seeds:state.seeds,spins:state.spins,reels:reels.map(i=>symbols[i].name),message,lastPayout,totalSpins:state.totalSpins,wins:state.wins,claimedDays:state.claimedDays,claimedTasks:state.claimedTasks,coupons:state.coupons,hamster:{name:state.name,theme:state.theme},tasks:tasks.map(t=>({id:t.id,progress:Math.min(taskProgress(t.id),t.target),target:t.target,claimed:state.claimedTasks.includes(t.id)})),storage:'Firestore server transactions'});
function confetti(){const wrap=document.createElement('div');wrap.className='confetti';wrap.setAttribute('aria-hidden','true');for(let i=0;i<25;i++){const p=document.createElement('i');p.style.cssText=`--x:${Math.random()*100}vw;--delay:${Math.random()*.4}s;--rotate:${Math.random()*720}deg;background:${['#8bbf9d','#f3bc67','#dba4a2','#b4a6cd'][i%4]}`;wrap.append(p);}document.body.append(wrap);setTimeout(()=>wrap.remove(),2400);}
function openModal(body){modalReturn=document.activeElement;const root=document.getElementById('modal-root');root.innerHTML=`<div class="modal-backdrop"><section class="modal" role="dialog" aria-modal="true" aria-labelledby="modal-title"><button class="modal-close icon-button" data-action="close" aria-label="Close dialog">×</button>${body}</section></div>`;root.querySelector('button').focus();document.body.style.overflow='hidden';}
function closeModal(){document.getElementById('modal-root').innerHTML='';document.body.style.overflow='';if(modalReturn?.isConnected)modalReturn.focus();}
function redeem(id){if(!requireVerified())return;const p=products.find(x=>x.id===id);if(!p||state.seeds<p.cost)return;openModal(`<span class="modal-art ${p.color}">${img(p.img,p.name)}</span><h2 id="modal-title">${esc(p.name)}</h2><p>Exchange ${p.cost} seeds for a bakery coupon. Staff will validate it when you collect your treat.</p><button class="button wide" data-action="confirm-redeem" data-id="${p.id}">Make it mine · ${p.cost} seeds</button>`);}
function couponModal(id){const c=state.coupons.find(c=>c.id===id);if(!c||c.used)return;openModal(`<span class="modal-gift">${icon('rewards')}</span><h2 id="modal-title">${esc(c.name)}</h2><p>Show this code to our staff when collecting your treat. Each coupon is valid once.</p><div class="coupon-code">${c.code}</div><button class="button wide" data-action="close">Done</button>`);}
async function action(button){const act=button.dataset.action,id=button.dataset.id;if(act==='close')return closeModal();if(act==='spin')return startSpin();if(busy)return;
try{
 if(act==='sound'){state.sound=!state.sound;render();return;}
 if(act==='gift'){if(!requireVerified())return;await run('daily');closeModal();render();toast('Your daily spins are ready!');return;}
 if(act==='odds'){openModal(`<h2 id="modal-title">A little luck, every day.</h2><p>Each play uses one spin. A loss gives no seeds; your saved seeds stay yours.</p><div class="odds-row"><b>No match · ${settings.lossPercent}%</b><span>0 seeds</span></div><div class="odds-row"><b>Pair · ${100-settings.lossPercent-settings.jackpotPercent}%</b><span>${settings.pairSeeds} seeds</span></div><div class="odds-row"><b>Jackpot · ${settings.jackpotPercent}%</b><span>${settings.jackpotSeeds} seeds</span></div><p>Collect daily gifts or scan a purchase code for more spins.</p><button class="button wide" data-action="close">Let’s play</button>`);return;}
 if(act==='redeem')return redeem(id);
 if(act==='confirm-redeem'){await run('redeem',{rewardId:id});closeModal();render();toast('Your coupon is ready. Show it to our staff.');return;}
 if(act==='coupon')return couponModal(id);
 if(act==='task'){const t=tasks.find(t=>t.id===id);if(!t)return;if(taskProgress(id)<t.target)return go(id==='visit'?'rewards':id==='style'?'hamster':'play');await run('task',{taskId:id});render();toast('Extra spins added!');return;}
 if(act==='theme'){draft.theme=button.dataset.theme;render();return;}
 if(act==='save-hamster'){await run('profile',{name:draft.name.trim()||'Bun',theme:draft.theme});render();toast('Your hamster is saved.');return;}
 if(act==='account')return accountModal();
 if(act==='register'||act==='login'){if(!document.getElementById('account-form').reportValidity())return;busy=true;const email=document.getElementById('account-email').value.trim(),password=document.getElementById('account-password').value;applySnapshot(await cloud[act](email,password));closeModal();render();toast(act==='register'?'Check your email to verify your account.':'Welcome back!');return;}
 if(act==='forgot'){await cloud.resetPassword(document.getElementById('account-email').value.trim());toast('Password reset requested. Check your email.');return;}
 if(act==='verify'){busy=true;applySnapshot(await cloud.refreshVerification());render();toast(cloud.account().emailVerified?'Email verified. Your daily gifts and purchase codes are ready.':'Please click the verification link in your email first.');return;}
 if(act==='resend'){await cloud.resendVerification();toast('Verification email sent.');return;}
 if(act==='logout'){busy=true;applySnapshot(await cloud.logout());tab='play';render();toast('Signed out. Sign back in to restore your saved progress.');return;}
 if(act==='purchase')return purchaseModal();
 if(act==='claim-code'){const code=document.getElementById('purchase-code').value.trim();sessionStorage.setItem('hg_purchase_code',code);if(!requireVerified())return;const result=await run('purchase',{code});sessionStorage.removeItem('hg_purchase_code');closeModal();render();toast(`Purchase confirmed. +${result.spinsAdded} spins!`);return;}
 if(act==='retry')return initLive();
}catch(e){showCloudError(e);}finally{busy=false;}}

document.addEventListener('click',event=>{const b=event.target.closest('button, a[data-tab]');if(b&&!b.disabled){if(b.dataset.tab){event.preventDefault();go(b.dataset.tab);}else if(b.dataset.action)void action(b);}if(event.target.classList.contains('modal-backdrop'))closeModal();});
document.addEventListener('input',event=>{if(event.target.id==='hamster-name'){draft.name=event.target.value;document.getElementById('preview-name').textContent=draft.name||'Bun';}});
document.addEventListener('keydown',event=>{const modal=document.querySelector('.modal');if(event.key==='Escape'){closeModal();return;}if(modal&&event.key==='Tab'){const list=[...modal.querySelectorAll('button:not(:disabled),input,a[href]')],first=list[0],last=list.at(-1);if(event.shiftKey&&document.activeElement===first){event.preventDefault();last.focus();}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus();}return;}if(event.code==='Space'&&tab==='play'&&!modal&&!event.target.closest('button,input,a')){event.preventDefault();startSpin();}});
function applySnapshot(result){if(result.settings){settings=result.settings;gifts=settings.dailySpins;products=settings.rewards.filter(r=>r.active);}if(result.player)state={...state,...result.player};if(result.coupons)state.coupons=result.coupons.map(c=>({...c,used:c.status==='used'}));if(result.coupon)state.coupons.unshift({...result.coupon,used:false});if(result.serverNow)serverOffset=result.serverNow-Date.now();serverDay=result.dayKey||serverDay;connected=true;}
async function run(action,data={}){busy=true;try{const result=await cloud.mutate(action,data);applySnapshot(result);return result;}finally{busy=false;}}
function nextGiftDay(){const previous=new Date(Date.now()+serverOffset+6*3600000-86400000).toISOString().slice(0,10);return state.lastDailyDate===previous?(state.dailyDay+1)%7:0;}
function showCloudError(e){console.error(e);toast(e.message||'Could not connect. Please try again.');}
function requireVerified(){const u=cloud.account();if(!u||u.isAnonymous){accountModal();return false;}if(!u.emailVerified){closeModal();tab='hamster';render();toast('Verify your email to claim daily gifts, purchases, and bakery treats.');return false;}return true;}
function accountPanel(){const u=cloud.account();return `<section class="panel account-panel"><span class="eyebrow">YOUR BAKERY ACCOUNT</span><h3>${u?.isAnonymous?'Keep your little wins.':'Your progress, wherever you play.'}</h3><p>${u?.isAnonymous?'Register to save this guest progress and unlock daily gifts and purchase rewards.':esc(u?.email||'')}</p><div class="playground-actions">${u?.isAnonymous?'<button class="button" data-action="account">Register / sign in</button>':`${!u?.emailVerified?'<button class="button" data-action="verify">I verified my email</button><button class="text-button" data-action="resend">Resend email</button>':''}<button class="text-button" data-action="logout">Sign out</button>`}</div></section>`;}
function accountModal(){openModal(`<h2 id="modal-title">Keep your little wins.</h2><p>Register to save your guest progress. Signing into an existing account restores that account’s progress.</p><form id="account-form"><label>Email<input id="account-email" type="email" autocomplete="email" required></label><label>Password<input id="account-password" type="password" minlength="8" autocomplete="current-password" required></label><button type="button" class="button wide" data-action="register">Register and save progress</button><button type="button" class="button secondary wide" data-action="login">Sign into an existing account</button><button type="button" class="text-button" data-action="forgot">Forgot password?</button></form>`);}
function purchasePanel(){return `<section class="panel purchase-panel"><div><span class="eyebrow">A LITTLE EXTRA WITH YOUR BREAD</span><h3>Bought something delicious?</h3><p>Scan the reward QR on your bread or receipt with your phone camera, or enter its code here.</p></div><button class="button" data-action="purchase">Claim purchase spins</button></section>`;}
function purchaseModal(){openModal(`<span class="modal-gift">${icon('spin')}</span><h2 id="modal-title">Bread brings more spins.</h2><p>Enter the unique reward code from your bread package or receipt. Each purchase code can be used once.</p><input id="purchase-code" value="${esc(sessionStorage.getItem('hg_purchase_code')||'')}" autocomplete="off" placeholder="Paste code or QR link"><button class="button wide" data-action="claim-code">Claim my spins</button>`);}
function openMoreSpins(){openModal(`<h2 id="modal-title">Fresh spins are coming.</h2><p>Claim today’s gift, finish a task, or use a purchase code from your bread or receipt.</p><button class="button wide" data-action="gift">Claim daily gift</button><button class="button secondary wide" data-action="purchase">Enter purchase code</button>`);}
async function initLive(){app.innerHTML='<div class="shell"><section class="panel"><h1>Opening the bakery…</h1><p>Connecting to your saved progress.</p></section></div>';try{applySnapshot(await cloud.boot());draft={name:state.name,theme:state.theme};render();const url=new URL(location.href),code=url.searchParams.get('code')||new URLSearchParams(url.hash.slice(1)).get('code');if(code){sessionStorage.setItem('hg_purchase_code',code);history.replaceState(null,'',url.pathname);purchaseModal();}}catch(e){app.innerHTML='<div class="shell"><section class="panel"><h2>The bakery could not connect.</h2><p>Please check your connection and try again.</p><button class="button" data-action="retry">Try again</button></section></div>';showCloudError(e);}}
document.addEventListener('visibilitychange',async()=>{if(document.visibilityState==='visible'&&connected&&!spinning&&!busy){try{applySnapshot(await cloud.load());render();}catch(e){showCloudError(e);}}});

initLive();
